version: "3.8"
services:
  client:
    build: ./client
    image: sof2team15/hike-tracker:client
    ports:
      - 3000:3000
    volumes:
      - "./client:/app"
      - /app/node_modules/
  
  server:
    build: ./server
    image: sof2team15/hike-tracker:server
    ports:
      - 3001:3001
    volumes:
      - "./server:/app"
      - /app/node_modules/
